"""Create initial tables.

Revision ID: 24cc9288ef0a
Revises: 
Create Date: 2024-02-22 15:16:56.979712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24cc9288ef0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('IPAddress', sa.String(length=255), nullable=False),
    sa.Column('itemName', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('IPAddress', sa.String(length=255), nullable=False),
    sa.Column('SelectedLanguage', sa.String(length=50), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('IPAddress', sa.String(length=255), nullable=False),
    sa.Column('sessionStart', sa.DateTime(), nullable=False),
    sa.Column('sessionEnd', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promotion_clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('IPAddress', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venmo_clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('IPAddress', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('VenmoClicks')
    op.drop_table('LanguageSelections')
    op.drop_table('CartItems')
    op.drop_table('PromotionClicks')
    op.drop_table('PageSessions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PageSessions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('IPAddress', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('sessionStart', mysql.DATETIME(), nullable=True),
    sa.Column('sessionEnd', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('PromotionClicks',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('IPAddress', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('CartItems',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('IPAddress', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('itemName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('LanguageSelections',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('IPAddress', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('SelectedLanguage', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('CreatedAt', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('VenmoClicks',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('IPAddress', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('venmo_clicks')
    op.drop_table('promotion_clicks')
    op.drop_table('page_sessions')
    op.drop_table('language_selections')
    op.drop_table('cart_items')
    # ### end Alembic commands ###
